ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)



LIBS+=drvr

EXTRA_SILENT_VARIANTS+=$(SECTION)

ifndef USEFILE
USEFILE=$(PROJECT_ROOT)/$(NAME).use
endif


-include $(PROJECT_ROOT)/roots.mk
#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

NAME =wdtkick
include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/$(SECTION)/pinfo.mk
include $(MKFILES_ROOT)/qtargets.mk