ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

INSTALLDIR = sbin

include $(MKFILES_ROOT)/qmacros.mk

-include $(PROJECT_ROOT)/roots.mk
#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################


ifeq ($(VARIANT3),) 
# Due to a change 2 years ago, targets that have 
# the cpu-endian variant collapsed are named fs-etfs-nand2048. 
NAME = fs-etfs-nand2048
else
NAME = fs-etfs-$(VARIANT3)
endif 

EXTRA_SILENT_VARIANTS+=$(VARIANT2) $(VARIANT3) 
USEFILE = $(PROJECT_ROOT)/etfs.use

EXTRA_INCVPATH += $(PRODUCT_ROOT)

LIBS = 	etfs

# If the etfs headers/libraries aren't present on the system, kill
# the compiles.
ifeq ($(call FIND_HDR_DIR,nto,usr/include,fs/etfs.h),)
TARGET_BUILD=@$(ECHO_HOST) ETFS headers/libraries not present on system
TARGET_INSTALL=
SRCS=
endif

include $(PROJECT_ROOT)/$(SECTION)/pinfo.mk
include $(MKFILES_ROOT)/qtargets.mk
